# Generated by Django 4.2.6 on 2023-10-30 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CalcApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calchist',
            name='id',
        ),
        migrations.AddField(
            model_name='calchist',
            name='hist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
